# spark-driver-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-driver        # pick any name you like
  namespace: spark-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: spark-demo
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps","persistentvolumeclaims"]
  verbs: ["*"]                # minimise later if you wish
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rb
  namespace: spark-demo
subjects:
- kind: ServiceAccount
  name: spark-driver
  namespace: spark-demo
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io
